image: node:lts
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run buildProd
    - cp ./public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master